# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 822)
        MainWindow.setMinimumSize(QtCore.QSize(513, 822))
        MainWindow.setMaximumSize(QtCore.QSize(513, 822))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 230, 491, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(10, 0, 461, 525))
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.manual_test_push_openpc = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_openpc.setObjectName("manual_test_push_openpc")
        self.horizontalLayout_2.addWidget(self.manual_test_push_openpc)
        self.manual_test_push_closepc = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_closepc.setObjectName("manual_test_push_closepc")
        self.horizontalLayout_2.addWidget(self.manual_test_push_closepc)
        self.push_reset = QtWidgets.QPushButton(self.widget)
        self.push_reset.setObjectName("push_reset")
        self.horizontalLayout_2.addWidget(self.push_reset)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.widget)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_6.addWidget(self.line_18, 3, 1, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.widget)
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_6.addWidget(self.line_20, 1, 2, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.widget)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_6.addWidget(self.line_19, 1, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.manual_test_push_rs232 = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_rs232.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_rs232.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_rs232.setObjectName("manual_test_push_rs232")
        self.gridLayout_3.addWidget(self.manual_test_push_rs232, 0, 0, 1, 1)
        self.manual_test_push_485 = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_485.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_485.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_485.setObjectName("manual_test_push_485")
        self.gridLayout_3.addWidget(self.manual_test_push_485, 1, 0, 1, 1)
        self.manual_test_push_can = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_can.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_can.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_can.setObjectName("manual_test_push_can")
        self.gridLayout_3.addWidget(self.manual_test_push_can, 2, 0, 1, 1)
        self.manual_test_push_do_on = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_do_on.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_do_on.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_do_on.setObjectName("manual_test_push_do_on")
        self.gridLayout_3.addWidget(self.manual_test_push_do_on, 3, 0, 1, 1)
        self.manual_test_push_do_off = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_do_off.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_do_off.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_do_off.setObjectName("manual_test_push_do_off")
        self.gridLayout_3.addWidget(self.manual_test_push_do_off, 4, 0, 1, 1)
        self.manual_test_push_bootlight = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_bootlight.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_bootlight.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_bootlight.setObjectName("manual_test_push_bootlight")
        self.gridLayout_3.addWidget(self.manual_test_push_bootlight, 5, 0, 1, 1)
        self.manual_test_push_emc_on = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_emc_on.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_emc_on.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_emc_on.setObjectName("manual_test_push_emc_on")
        self.gridLayout_3.addWidget(self.manual_test_push_emc_on, 6, 0, 1, 1)
        self.manual_test_push_emc_off = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_emc_off.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_emc_off.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_emc_off.setObjectName("manual_test_push_emc_off")
        self.gridLayout_3.addWidget(self.manual_test_push_emc_off, 7, 0, 1, 1)
        self.manual_test_push_charge_groud = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_charge_groud.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_charge_groud.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_charge_groud.setObjectName("manual_test_push_charge_groud")
        self.gridLayout_3.addWidget(self.manual_test_push_charge_groud, 8, 0, 1, 1)
        self.manual_test_push_charge_brake = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_charge_brake.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_charge_brake.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_charge_brake.setObjectName("manual_test_push_charge_brake")
        self.gridLayout_3.addWidget(self.manual_test_push_charge_brake, 9, 0, 1, 1)
        self.manual_test_push_brake_on = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_brake_on.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_brake_on.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_brake_on.setObjectName("manual_test_push_brake_on")
        self.gridLayout_3.addWidget(self.manual_test_push_brake_on, 10, 0, 1, 1)
        self.manual_test_push_brake_off = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_brake_off.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_brake_off.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_brake_off.setObjectName("manual_test_push_brake_off")
        self.gridLayout_3.addWidget(self.manual_test_push_brake_off, 11, 0, 1, 1)
        self.manual_test_push_di_brake = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_di_brake.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_di_brake.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_di_brake.setObjectName("manual_test_push_di_brake")
        self.gridLayout_3.addWidget(self.manual_test_push_di_brake, 12, 0, 1, 1)
        self.manual_test_push_di_ground = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_di_ground.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_di_ground.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_di_ground.setObjectName("manual_test_push_di_ground")
        self.gridLayout_3.addWidget(self.manual_test_push_di_ground, 13, 0, 1, 1)
        self.manual_test_push_delay_brake = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_delay_brake.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_delay_brake.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_delay_brake.setObjectName("manual_test_push_delay_brake")
        self.gridLayout_3.addWidget(self.manual_test_push_delay_brake, 14, 0, 1, 1)
        self.manual_test_push_brake_on_2 = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_brake_on_2.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_brake_on_2.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_brake_on_2.setObjectName("manual_test_push_brake_on_2")
        self.gridLayout_3.addWidget(self.manual_test_push_brake_on_2, 15, 0, 1, 1)
        self.manual_test_push_warn_on = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_warn_on.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_warn_on.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_warn_on.setObjectName("manual_test_push_warn_on")
        self.gridLayout_3.addWidget(self.manual_test_push_warn_on, 16, 0, 1, 1)
        self.manual_test_push_warn_off = QtWidgets.QPushButton(self.widget)
        self.manual_test_push_warn_off.setMinimumSize(QtCore.QSize(122, 21))
        self.manual_test_push_warn_off.setMaximumSize(QtCore.QSize(16777215, 21))
        self.manual_test_push_warn_off.setObjectName("manual_test_push_warn_off")
        self.gridLayout_3.addWidget(self.manual_test_push_warn_off, 17, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.manual_label_state_rs232 = QtWidgets.QLabel(self.widget)
        self.manual_label_state_rs232.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_rs232.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_rs232.setText("")
        self.manual_label_state_rs232.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_rs232.setObjectName("manual_label_state_rs232")
        self.gridLayout_4.addWidget(self.manual_label_state_rs232, 0, 0, 1, 1)
        self.manual_label_state_rs485 = QtWidgets.QLabel(self.widget)
        self.manual_label_state_rs485.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_rs485.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_rs485.setText("")
        self.manual_label_state_rs485.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_rs485.setObjectName("manual_label_state_rs485")
        self.gridLayout_4.addWidget(self.manual_label_state_rs485, 1, 0, 1, 1)
        self.manual_label_state_can = QtWidgets.QLabel(self.widget)
        self.manual_label_state_can.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_can.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_can.setText("")
        self.manual_label_state_can.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_can.setObjectName("manual_label_state_can")
        self.gridLayout_4.addWidget(self.manual_label_state_can, 2, 0, 1, 1)
        self.manual_label_state_do_on = QtWidgets.QLabel(self.widget)
        self.manual_label_state_do_on.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_do_on.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_do_on.setText("")
        self.manual_label_state_do_on.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_do_on.setObjectName("manual_label_state_do_on")
        self.gridLayout_4.addWidget(self.manual_label_state_do_on, 3, 0, 1, 1)
        self.manual_label_state_do_off = QtWidgets.QLabel(self.widget)
        self.manual_label_state_do_off.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_do_off.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_do_off.setText("")
        self.manual_label_state_do_off.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_do_off.setObjectName("manual_label_state_do_off")
        self.gridLayout_4.addWidget(self.manual_label_state_do_off, 4, 0, 1, 1)
        self.manual_label_state_bootlight = QtWidgets.QLabel(self.widget)
        self.manual_label_state_bootlight.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_bootlight.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_bootlight.setText("")
        self.manual_label_state_bootlight.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_bootlight.setObjectName("manual_label_state_bootlight")
        self.gridLayout_4.addWidget(self.manual_label_state_bootlight, 5, 0, 1, 1)
        self.manual_label_state_emc_on = QtWidgets.QLabel(self.widget)
        self.manual_label_state_emc_on.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_emc_on.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_emc_on.setText("")
        self.manual_label_state_emc_on.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_emc_on.setObjectName("manual_label_state_emc_on")
        self.gridLayout_4.addWidget(self.manual_label_state_emc_on, 6, 0, 1, 1)
        self.manual_label_state_emc_off = QtWidgets.QLabel(self.widget)
        self.manual_label_state_emc_off.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_emc_off.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_emc_off.setText("")
        self.manual_label_state_emc_off.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_emc_off.setObjectName("manual_label_state_emc_off")
        self.gridLayout_4.addWidget(self.manual_label_state_emc_off, 7, 0, 1, 1)
        self.manual_label_state_charge_ground = QtWidgets.QLabel(self.widget)
        self.manual_label_state_charge_ground.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_charge_ground.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_charge_ground.setText("")
        self.manual_label_state_charge_ground.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_charge_ground.setObjectName("manual_label_state_charge_ground")
        self.gridLayout_4.addWidget(self.manual_label_state_charge_ground, 8, 0, 1, 1)
        self.manual_label_state_charge_brake = QtWidgets.QLabel(self.widget)
        self.manual_label_state_charge_brake.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_charge_brake.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_charge_brake.setText("")
        self.manual_label_state_charge_brake.setTextFormat(QtCore.Qt.RichText)
        self.manual_label_state_charge_brake.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_charge_brake.setObjectName("manual_label_state_charge_brake")
        self.gridLayout_4.addWidget(self.manual_label_state_charge_brake, 9, 0, 1, 1)
        self.manual_label_state_brake_on = QtWidgets.QLabel(self.widget)
        self.manual_label_state_brake_on.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_brake_on.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_brake_on.setText("")
        self.manual_label_state_brake_on.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_brake_on.setObjectName("manual_label_state_brake_on")
        self.gridLayout_4.addWidget(self.manual_label_state_brake_on, 10, 0, 1, 1)
        self.manual_label_state_brake_off = QtWidgets.QLabel(self.widget)
        self.manual_label_state_brake_off.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_brake_off.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_brake_off.setText("")
        self.manual_label_state_brake_off.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_brake_off.setObjectName("manual_label_state_brake_off")
        self.gridLayout_4.addWidget(self.manual_label_state_brake_off, 11, 0, 1, 1)
        self.manual_label_state_di_off = QtWidgets.QLabel(self.widget)
        self.manual_label_state_di_off.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_di_off.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_di_off.setText("")
        self.manual_label_state_di_off.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_di_off.setObjectName("manual_label_state_di_off")
        self.gridLayout_4.addWidget(self.manual_label_state_di_off, 12, 0, 1, 1)
        self.manual_label_state_di_ground = QtWidgets.QLabel(self.widget)
        self.manual_label_state_di_ground.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_di_ground.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_di_ground.setText("")
        self.manual_label_state_di_ground.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_di_ground.setObjectName("manual_label_state_di_ground")
        self.gridLayout_4.addWidget(self.manual_label_state_di_ground, 13, 0, 1, 1)
        self.manual_label_state_delay_brake = QtWidgets.QLabel(self.widget)
        self.manual_label_state_delay_brake.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_delay_brake.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_delay_brake.setText("")
        self.manual_label_state_delay_brake.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_delay_brake.setObjectName("manual_label_state_delay_brake")
        self.gridLayout_4.addWidget(self.manual_label_state_delay_brake, 14, 0, 1, 1)
        self.manual_label_state_delay_on = QtWidgets.QLabel(self.widget)
        self.manual_label_state_delay_on.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_delay_on.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_delay_on.setText("")
        self.manual_label_state_delay_on.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_delay_on.setObjectName("manual_label_state_delay_on")
        self.gridLayout_4.addWidget(self.manual_label_state_delay_on, 15, 0, 1, 1)
        self.manual_label_state_warn_on = QtWidgets.QLabel(self.widget)
        self.manual_label_state_warn_on.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_warn_on.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_warn_on.setText("")
        self.manual_label_state_warn_on.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_warn_on.setObjectName("manual_label_state_warn_on")
        self.gridLayout_4.addWidget(self.manual_label_state_warn_on, 16, 0, 1, 1)
        self.manual_label_state_warn_off = QtWidgets.QLabel(self.widget)
        self.manual_label_state_warn_off.setMinimumSize(QtCore.QSize(21, 21))
        self.manual_label_state_warn_off.setMaximumSize(QtCore.QSize(21, 21))
        self.manual_label_state_warn_off.setText("")
        self.manual_label_state_warn_off.setPixmap(QtGui.QPixmap("x.png"))
        self.manual_label_state_warn_off.setObjectName("manual_label_state_warn_off")
        self.gridLayout_4.addWidget(self.manual_label_state_warn_off, 17, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.widget)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_5.addWidget(self.line_17, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 2, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.widget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_6.addWidget(self.line_15, 2, 0, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.widget)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_6.addWidget(self.line_16, 2, 2, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.widget)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_6.addWidget(self.line_21, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget1 = QtWidgets.QWidget(self.tab_4)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 471, 521))
        self.widget1.setObjectName("widget1")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_11.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.line_30 = QtWidgets.QFrame(self.widget1)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_11.addWidget(self.line_30, 6, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.widget1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_11.addWidget(self.progressBar, 8, 1, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.widget1)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout_11.addWidget(self.line_29, 5, 2, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.widget1)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_11.addWidget(self.line_23, 3, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.widget1)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_11.addWidget(self.line_13, 2, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.widget1)
        self.label_69.setObjectName("label_69")
        self.gridLayout_11.addWidget(self.label_69, 3, 1, 1, 1)
        self.line_32 = QtWidgets.QFrame(self.widget1)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout_11.addWidget(self.line_32, 8, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.widget1)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_11.addWidget(self.line_14, 0, 1, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.widget1)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_11.addWidget(self.line_12, 1, 2, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_8.addWidget(self.line, 1, 0, 1, 1)
        self.atuo_label_brake_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_brake_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_brake_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_brake_state.setText("")
        self.atuo_label_brake_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_brake_state.setObjectName("atuo_label_brake_state")
        self.gridLayout_8.addWidget(self.atuo_label_brake_state, 9, 0, 1, 1)
        self.atuo_label_do_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_do_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_do_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_do_state.setText("")
        self.atuo_label_do_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_do_state.setObjectName("atuo_label_do_state")
        self.gridLayout_8.addWidget(self.atuo_label_do_state, 5, 0, 1, 1)
        self.atuo_label_delay_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_delay_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_delay_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_delay_state.setText("")
        self.atuo_label_delay_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_delay_state.setObjectName("atuo_label_delay_state")
        self.gridLayout_8.addWidget(self.atuo_label_delay_state, 11, 0, 1, 1)
        self.atuo_label_can_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_can_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_can_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_can_state.setText("")
        self.atuo_label_can_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_can_state.setObjectName("atuo_label_can_state")
        self.gridLayout_8.addWidget(self.atuo_label_can_state, 4, 0, 1, 1)
        self.atuo_label_rs232_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_rs232_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_rs232_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_rs232_state.setText("")
        self.atuo_label_rs232_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_rs232_state.setObjectName("atuo_label_rs232_state")
        self.gridLayout_8.addWidget(self.atuo_label_rs232_state, 2, 0, 1, 1)
        self.atuo_label_poweroff_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_poweroff_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_poweroff_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_poweroff_state.setText("")
        self.atuo_label_poweroff_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_poweroff_state.setObjectName("atuo_label_poweroff_state")
        self.gridLayout_8.addWidget(self.atuo_label_poweroff_state, 14, 0, 1, 1)
        self.atuo_label_poweron_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_poweron_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_poweron_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_poweron_state.setText("")
        self.atuo_label_poweron_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_poweron_state.setObjectName("atuo_label_poweron_state")
        self.gridLayout_8.addWidget(self.atuo_label_poweron_state, 13, 0, 1, 1)
        self.atuo_label_rs485_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_rs485_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_rs485_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_rs485_state.setText("")
        self.atuo_label_rs485_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_rs485_state.setObjectName("atuo_label_rs485_state")
        self.gridLayout_8.addWidget(self.atuo_label_rs485_state, 3, 0, 1, 1)
        self.atuo_label_warninglight_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_warninglight_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_warninglight_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_warninglight_state.setText("")
        self.atuo_label_warninglight_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_warninglight_state.setObjectName("atuo_label_warninglight_state")
        self.gridLayout_8.addWidget(self.atuo_label_warninglight_state, 12, 0, 1, 1)
        self.atuo_label_di_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_di_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_di_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_di_state.setText("")
        self.atuo_label_di_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_di_state.setObjectName("atuo_label_di_state")
        self.gridLayout_8.addWidget(self.atuo_label_di_state, 10, 0, 1, 1)
        self.atuo_label_charge_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_charge_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_charge_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_charge_state.setText("")
        self.atuo_label_charge_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_charge_state.setObjectName("atuo_label_charge_state")
        self.gridLayout_8.addWidget(self.atuo_label_charge_state, 8, 0, 1, 1)
        self.atuo_label_emc_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_emc_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_emc_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_emc_state.setText("")
        self.atuo_label_emc_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_emc_state.setObjectName("atuo_label_emc_state")
        self.gridLayout_8.addWidget(self.atuo_label_emc_state, 7, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.widget1)
        self.label_61.setObjectName("label_61")
        self.gridLayout_8.addWidget(self.label_61, 0, 0, 1, 1)
        self.atuo_label_bootlight_state = QtWidgets.QLabel(self.widget1)
        self.atuo_label_bootlight_state.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_bootlight_state.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_bootlight_state.setText("")
        self.atuo_label_bootlight_state.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_bootlight_state.setObjectName("atuo_label_bootlight_state")
        self.gridLayout_8.addWidget(self.atuo_label_bootlight_state, 6, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.widget1)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_9.addWidget(self.line_4, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.widget1)
        self.label_19.setMinimumSize(QtCore.QSize(0, 21))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.widget1)
        self.label_37.setMinimumSize(QtCore.QSize(0, 21))
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 7, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget1)
        self.label_33.setMinimumSize(QtCore.QSize(0, 21))
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 10, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget1)
        self.label_29.setMinimumSize(QtCore.QSize(0, 21))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 12, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget1)
        self.label_31.setMinimumSize(QtCore.QSize(0, 21))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 13, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget1)
        self.label_21.setMinimumSize(QtCore.QSize(0, 21))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.widget1)
        self.label_38.setMinimumSize(QtCore.QSize(0, 21))
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 8, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.widget1)
        self.label_59.setObjectName("label_59")
        self.gridLayout.addWidget(self.label_59, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget1)
        self.label_22.setMinimumSize(QtCore.QSize(0, 21))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget1)
        self.label_23.setMinimumSize(QtCore.QSize(0, 21))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 9, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.widget1)
        self.label_36.setMinimumSize(QtCore.QSize(0, 21))
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 11, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget1)
        self.label_32.setMinimumSize(QtCore.QSize(0, 21))
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 15, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget1)
        self.label_20.setMinimumSize(QtCore.QSize(0, 21))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget1)
        self.label_30.setMinimumSize(QtCore.QSize(0, 21))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.atuo_line_text_warninglight = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_warninglight.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_warninglight.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_warninglight.setObjectName("atuo_line_text_warninglight")
        self.gridLayout_7.addWidget(self.atuo_line_text_warninglight, 12, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.widget1)
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 0, 0, 1, 1)
        self.atuo_line_text_can = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_can.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_can.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_can.setObjectName("atuo_line_text_can")
        self.gridLayout_7.addWidget(self.atuo_line_text_can, 4, 0, 1, 1)
        self.atuo_line_text_do = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_do.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_do.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_do.setObjectName("atuo_line_text_do")
        self.gridLayout_7.addWidget(self.atuo_line_text_do, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 1, 0, 1, 1)
        self.atuo_line_text_brake = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_brake.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_brake.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_brake.setObjectName("atuo_line_text_brake")
        self.gridLayout_7.addWidget(self.atuo_line_text_brake, 9, 0, 1, 1)
        self.atuo_line_text_bootlight = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_bootlight.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_bootlight.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_bootlight.setObjectName("atuo_line_text_bootlight")
        self.gridLayout_7.addWidget(self.atuo_line_text_bootlight, 6, 0, 1, 1)
        self.atuo_line_text_emc = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_emc.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_emc.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_emc.setObjectName("atuo_line_text_emc")
        self.gridLayout_7.addWidget(self.atuo_line_text_emc, 7, 0, 1, 1)
        self.atuo_line_text_poweroff = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_poweroff.setEnabled(False)
        self.atuo_line_text_poweroff.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_poweroff.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_poweroff.setObjectName("atuo_line_text_poweroff")
        self.gridLayout_7.addWidget(self.atuo_line_text_poweroff, 14, 0, 1, 1)
        self.atuo_line_text_rs232 = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_rs232.setEnabled(False)
        self.atuo_line_text_rs232.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_rs232.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_rs232.setReadOnly(True)
        self.atuo_line_text_rs232.setObjectName("atuo_line_text_rs232")
        self.gridLayout_7.addWidget(self.atuo_line_text_rs232, 2, 0, 1, 1)
        self.atuo_line_text_charge = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_charge.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_charge.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_charge.setObjectName("atuo_line_text_charge")
        self.gridLayout_7.addWidget(self.atuo_line_text_charge, 8, 0, 1, 1)
        self.atuo_line_text_delay = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_delay.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_delay.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_delay.setObjectName("atuo_line_text_delay")
        self.gridLayout_7.addWidget(self.atuo_line_text_delay, 11, 0, 1, 1)
        self.atuo_line_text_poweron = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_poweron.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_poweron.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_poweron.setObjectName("atuo_line_text_poweron")
        self.gridLayout_7.addWidget(self.atuo_line_text_poweron, 13, 0, 1, 1)
        self.atuo_line_text_rs485 = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_rs485.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_rs485.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_rs485.setObjectName("atuo_line_text_rs485")
        self.gridLayout_7.addWidget(self.atuo_line_text_rs485, 3, 0, 1, 1)
        self.atuo_line_text_di = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_di.setMinimumSize(QtCore.QSize(0, 21))
        self.atuo_line_text_di.setMaximumSize(QtCore.QSize(16777215, 21))
        self.atuo_line_text_di.setObjectName("atuo_line_text_di")
        self.gridLayout_7.addWidget(self.atuo_line_text_di, 10, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.widget1)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_9.addWidget(self.line_5, 0, 3, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 1, 1, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.widget1)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_11.addWidget(self.line_26, 6, 0, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.widget1)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_11.addWidget(self.line_22, 7, 1, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.widget1)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout_11.addWidget(self.line_31, 7, 0, 1, 1)
        self.atuo_line_text_total = QtWidgets.QLineEdit(self.widget1)
        self.atuo_line_text_total.setObjectName("atuo_line_text_total")
        self.gridLayout_11.addWidget(self.atuo_line_text_total, 4, 1, 1, 1)
        self.atuo_push_button_test = QtWidgets.QPushButton(self.widget1)
        self.atuo_push_button_test.setObjectName("atuo_push_button_test")
        self.gridLayout_11.addWidget(self.atuo_push_button_test, 5, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.widget1)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_11.addWidget(self.line_11, 1, 0, 1, 1)
        self.line_33 = QtWidgets.QFrame(self.widget1)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout_11.addWidget(self.line_33, 8, 2, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.widget1)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_11.addWidget(self.line_28, 4, 2, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.widget1)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_11.addWidget(self.line_24, 4, 0, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.widget1)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_11.addWidget(self.line_25, 5, 0, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.widget1)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_11.addWidget(self.line_27, 3, 2, 1, 1)
        self.atuo_push_button_report = QtWidgets.QPushButton(self.widget1)
        self.atuo_push_button_report.setObjectName("atuo_push_button_report")
        self.gridLayout_11.addWidget(self.atuo_push_button_report, 6, 1, 1, 1)
        self.line_34 = QtWidgets.QFrame(self.widget1)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout_11.addWidget(self.line_34, 9, 1, 1, 1)
        self.atuo_label_rs232_state_3 = QtWidgets.QLabel(self.tab_4)
        self.atuo_label_rs232_state_3.setGeometry(QtCore.QRect(220, 230, 21, 21))
        self.atuo_label_rs232_state_3.setMinimumSize(QtCore.QSize(21, 21))
        self.atuo_label_rs232_state_3.setMaximumSize(QtCore.QSize(21, 21))
        self.atuo_label_rs232_state_3.setText("")
        self.atuo_label_rs232_state_3.setPixmap(QtGui.QPixmap("x.png"))
        self.atuo_label_rs232_state_3.setObjectName("atuo_label_rs232_state_3")
        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 211))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_12.setSpacing(2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setMinimumSize(QtCore.QSize(0, 21))
        self.label_70.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_70.setObjectName("label_70")
        self.verticalLayout.addWidget(self.label_70)
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setMinimumSize(QtCore.QSize(0, 21))
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_71.setObjectName("label_71")
        self.verticalLayout.addWidget(self.label_71)
        self.gridLayout_10.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_ip = QtWidgets.QLineEdit(self.groupBox)
        self.line_ip.setMinimumSize(QtCore.QSize(0, 21))
        self.line_ip.setMaximumSize(QtCore.QSize(16777215, 21))
        self.line_ip.setObjectName("line_ip")
        self.verticalLayout_2.addWidget(self.line_ip)
        self.line_port = QtWidgets.QLineEdit(self.groupBox)
        self.line_port.setMinimumSize(QtCore.QSize(0, 21))
        self.line_port.setMaximumSize(QtCore.QSize(16777215, 21))
        self.line_port.setObjectName("line_port")
        self.verticalLayout_2.addWidget(self.line_port)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.push_connect = QtWidgets.QPushButton(self.groupBox)
        self.push_connect.setMinimumSize(QtCore.QSize(0, 21))
        self.push_connect.setMaximumSize(QtCore.QSize(16777215, 21))
        self.push_connect.setObjectName("push_connect")
        self.gridLayout_12.addWidget(self.push_connect, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 10, 251, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 231, 79))
        self.widget2.setObjectName("widget2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_16.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_74 = QtWidgets.QLabel(self.widget2)
        self.label_74.setMinimumSize(QtCore.QSize(0, 21))
        self.label_74.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_74.setObjectName("label_74")
        self.gridLayout_15.addWidget(self.label_74, 0, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.widget2)
        self.label_73.setMinimumSize(QtCore.QSize(0, 21))
        self.label_73.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_73.setObjectName("label_73")
        self.gridLayout_15.addWidget(self.label_73, 1, 0, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.widget2)
        self.label_75.setMinimumSize(QtCore.QSize(0, 21))
        self.label_75.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_75.setObjectName("label_75")
        self.gridLayout_15.addWidget(self.label_75, 2, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_76 = QtWidgets.QLabel(self.widget2)
        self.label_76.setMinimumSize(QtCore.QSize(0, 21))
        self.label_76.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_76.setObjectName("label_76")
        self.gridLayout_14.addWidget(self.label_76, 0, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.widget2)
        self.label_77.setMinimumSize(QtCore.QSize(0, 21))
        self.label_77.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_77.setObjectName("label_77")
        self.gridLayout_14.addWidget(self.label_77, 1, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.widget2)
        self.label_78.setMinimumSize(QtCore.QSize(0, 21))
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label_78.setObjectName("label_78")
        self.gridLayout_14.addWidget(self.label_78, 2, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_14, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        self.label_72.setGeometry(QtCore.QRect(10, 80, 231, 120))
        self.label_72.setObjectName("label_72")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manual_test_push_openpc.setText(_translate("MainWindow", "开机"))
        self.manual_test_push_closepc.setText(_translate("MainWindow", "关机"))
        self.push_reset.setText(_translate("MainWindow", "Reset"))
        self.manual_test_push_rs232.setText(_translate("MainWindow", "rs232测试"))
        self.manual_test_push_485.setText(_translate("MainWindow", "rs485测试"))
        self.manual_test_push_can.setText(_translate("MainWindow", "can测试"))
        self.manual_test_push_do_on.setText(_translate("MainWindow", "DO全开测试"))
        self.manual_test_push_do_off.setText(_translate("MainWindow", "DO全关测试"))
        self.manual_test_push_bootlight.setText(_translate("MainWindow", "bootlight测试"))
        self.manual_test_push_emc_on.setText(_translate("MainWindow", "emc输出开测试"))
        self.manual_test_push_emc_off.setText(_translate("MainWindow", "emc输出关测试"))
        self.manual_test_push_charge_groud.setText(_translate("MainWindow", "charge接地测试"))
        self.manual_test_push_charge_brake.setText(_translate("MainWindow", "charge断开测试"))
        self.manual_test_push_brake_on.setText(_translate("MainWindow", "brake输出24-12V测试"))
        self.manual_test_push_brake_off.setText(_translate("MainWindow", "brake输出关测试"))
        self.manual_test_push_di_brake.setText(_translate("MainWindow", "DI断开测试"))
        self.manual_test_push_di_ground.setText(_translate("MainWindow", "DI接地测试"))
        self.manual_test_push_delay_brake.setText(_translate("MainWindow", "delay断开测试"))
        self.manual_test_push_brake_on_2.setText(_translate("MainWindow", "delay闭合测试"))
        self.manual_test_push_warn_on.setText(_translate("MainWindow", "warninglight开测试"))
        self.manual_test_push_warn_off.setText(_translate("MainWindow", "warninglight关测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "手动测试"))
        self.label_69.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">总循环次数</p></body></html>"))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">状态</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">rs485测试</p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">bootlight测试</p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">brake输出测试</p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">delay测试</p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">warninglight测试</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">can测试</p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">emc输出测试</p></body></html>"))
        self.label_59.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">测试项</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DO测试</p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">charge测试</p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DI测试</p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">关机测试</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">rs232测试</p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">开机测试</p></body></html>"))
        self.atuo_line_text_warninglight.setText(_translate("MainWindow", "10"))
        self.label_60.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">测试次数</p></body></html>"))
        self.atuo_line_text_can.setText(_translate("MainWindow", "20"))
        self.atuo_line_text_do.setText(_translate("MainWindow", "20"))
        self.atuo_line_text_brake.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_bootlight.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_emc.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_poweroff.setText(_translate("MainWindow", "1"))
        self.atuo_line_text_rs232.setText(_translate("MainWindow", "1"))
        self.atuo_line_text_charge.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_delay.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_poweron.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_rs485.setText(_translate("MainWindow", "20"))
        self.atuo_line_text_di.setText(_translate("MainWindow", "10"))
        self.atuo_line_text_total.setText(_translate("MainWindow", "10"))
        self.atuo_push_button_test.setText(_translate("MainWindow", "一键自动测试"))
        self.atuo_push_button_report.setText(_translate("MainWindow", "一键生成报告"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "自动测试"))
        self.groupBox.setTitle(_translate("MainWindow", "connect"))
        self.label_70.setText(_translate("MainWindow", "IP"))
        self.label_71.setText(_translate("MainWindow", "PORT"))
        self.line_ip.setText(_translate("MainWindow", "192.168.192.6"))
        self.line_port.setText(_translate("MainWindow", "4822"))
        self.push_connect.setText(_translate("MainWindow", "connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "info"))
        self.label_74.setText(_translate("MainWindow", "MainVersion:"))
        self.label_73.setText(_translate("MainWindow", "GyroVersion:"))
        self.label_75.setText(_translate("MainWindow", "UID:"))
        self.label_76.setText(_translate("MainWindow", "unknown"))
        self.label_77.setText(_translate("MainWindow", "unknown"))
        self.label_78.setText(_translate("MainWindow", "unknown"))
        self.label_72.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">unknown</span></p></body></html>"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())